openapi: 3.0.0
info:
  title: 'Clothes Shop API'
  description: 'API documentation for Clothes Shop Web'
  version: 1.0.0
paths:
  /api/products:
    get:
      tags:
        - Products
      summary: 'List products'
      description: "Return a list of products with variants and categories.\nSupports optional pagination via `per_page` query param."
      operationId: 1bfaa78d1c2c3848ab8165c5dadcad3e
      responses:
        200:
          description: 'Products returned successfully'
tags:
  - name: Products
    description: Products
